name: Merge Tina media from master to staging

on:
  push:
    branches:
      - master

jobs:
  merge_to_staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge master into staging
        run: |
          git checkout staging
          git merge master
          git push origin staging